name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Fix permissions for mvnw script
    - name: Make mvnw executable
      run: chmod +x ./mvnw

    # Run Maven build
    - name: Build with Maven
      run: |
        ./mvnw clean package -DskipTests
  
    # Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ANZ_ACR_INSTANCE_NAME }}.azurecr.io  # Replace with your ACR login server
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ANZ_ACR_INSTANCE_NAME }}.azurecr.io/${{ secrets.ACR_IMAGE_NAME }}:${{ github.sha }} .

    # Push the Docker image to ACR
    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.ANZ_ACR_INSTANCE_NAME }}.azurecr.io/${{ secrets.ACR_IMAGE_NAME }}:${{ github.sha }}